### ISSUE TITLE
Separate table for Fall 2025 internship listings

### ISSUE THREAD

**Issue by arushi2610** [speedyapply/swe-college-jobs#7]
### Issue or Feature Request

With Fall 2024 internships nearing completion, I noticed that the current table has a list of mixed entries for Fall 2025 with those for Fall 2024. For improved clarity and organization, I propose creating a separate table specifically for Fall 2025 internship opportunities. I'd like to work on it , if possible.

**Comment by cullenwatson** [comment]
sure, you can work in it.

**Comment by cullenwatson** [comment]
going to close for now but you can pr. theres only around 200 jobs in the repo currently tho so not sure it's necessary till the fall jobs pick up.
