### ISSUE TITLE
position link should be added 

### ISSUE THREAD

**Issue by tejas-2232** [speedyapply/swe-college-jobs#8]
### Issue or Feature Request

**For every job listing, the link for that position should be added.**

**For ex:** If Software Engineer Intern Fall 24 position is open at Tesla then instead of adding Tesla link (www.tesla.com) the actual site link should be added ( https://www.tesla.com/careers/search/job/internship-fullstack-software-engineer-maps-self-driving-navigation-fall-2024-222614) 

> It will be time saving for applicants, they won't have to search it by going to company's career site.

**Comment by kirkwat** [comment]
For each job, there is an `Apply` button that links to the specific job posting. Is this what you were referring to?

**Comment by tejas-2232** [comment]
Oh yeah, sorry I totally missed it. How can I not see that 😂

Sorry Kirk.
